### ISSUE TITLE
Problem about load balance target

### ISSUE THREAD

**Issue by haonanw98** [tamer-eldeeb/deepNE#1]
@tamer-eldeeb 
Hi Tamer,  I have a question here:
How do we compute the performance of the load balancing algorithm here?

**Comment by haonanw98** [comment]
By the way, I have finished the power of k and have worked on other algorithms like random selecting or using hash selecting.

**Comment by tamer-eldeeb** [comment]
The metric we're using is the load difference between max loaded and min loaded partitions

**Comment by haonanw98** [comment]
I have fixed the code!
